version: '3.8'
services:
  db:
    image: postgres:16.0
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    env_file:
      - .env
    ports:
      - '${POSTGRES_PORT}:5432'
    volumes: 
      - .pgdata:/var/lib/postgresql/data
volumes:
  db:
    driver: local